language: android
android:
  components:
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
      - android-sdk-license-.+
script:
   - ./gradlew build
